In [1]:
import torch

In [ ]:
def multiples_of_ten(start, stop):
    
"""
  Returns a Tensor of dtype torch.float64 that contains all of the multiples of
  ten (in order) between start and stop, inclusive. If there are no multiples
  of ten in this range you should return an empty tensor of shape (0,).
  
  返回一个数据类型为torch.float64的张量，其中包含在开始和结尾（包含）之间的所有
  10的倍数。如果该范围内没有10的倍数，则返回一个形状为（0，）的空张量。

  Inputs:
  - start, stop: Integers with start <= stop specifying the range to create.

  Returns:
  - x: Tensor of dtype float64 giving multiples of ten between start and stop.
  """
    assert start <= stop
  #############################################################################
  #                    TODO: Implement this function                          #
  #############################################################################
  # Replace "pass" statement with your code
    x = []
    print(x)
    for i in torch.arange(start,stop+1):
        if(i%10 == 0):
            x.append(i)
    x = torch.tensor(x,dtype=torch.float64)
  #############################################################################
  #                            END OF YOUR CODE                               #
  #############################################################################
  return x

In [2]:
a=torch.tensor([0,1,2,3,4,5])
b=a[2:]
c=a.clone()
b[0]=10
c[0]=100
print(a)
print(b)
print(c)
print(a.storage().data_ptr())
print(b.storage().data_ptr())
print(c.storage().data_ptr())

tensor([ 0,  1, 10,  3,  4,  5])
tensor([10,  3,  4,  5])
tensor([100,   1,   2,   3,   4,   5])
3041243780480
3041243780480
3041243779456


In [9]:
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[[0,1,1],[0,0,2]])

tensor([1, 5, 7])


In [12]:
x=torch.tensor([0,1,2,3])
a=torch.arange(x.shape[0]-1,-1,-1)
print(a)

tensor([3, 2, 1, 0])


In [7]:
#cross validation
random = torch.rand(3, 5)
print(random)
x = random.chunk(5, 1)
print(x)
array = []
for i in range(5):
    array.append(x[i])
print(array)

tensor([[0.3998, 0.3943, 0.5559, 0.3950, 0.0277],
        [0.5608, 0.3193, 0.2274, 0.8187, 0.9385],
        [0.1028, 0.4477, 0.5916, 0.2279, 0.9061]])
(tensor([[0.3998],
        [0.5608],
        [0.1028]]), tensor([[0.3943],
        [0.3193],
        [0.4477]]), tensor([[0.5559],
        [0.2274],
        [0.5916]]), tensor([[0.3950],
        [0.8187],
        [0.2279]]), tensor([[0.0277],
        [0.9385],
        [0.9061]]))
[tensor([[0.3998],
        [0.5608],
        [0.1028]]), tensor([[0.3943],
        [0.3193],
        [0.4477]]), tensor([[0.5559],
        [0.2274],
        [0.5916]]), tensor([[0.3950],
        [0.8187],
        [0.2279]]), tensor([[0.0277],
        [0.9385],
        [0.9061]])]
